# Installs @@NAME@@ from its GitHub release. Generated by leduftw/playbook.
#
#   irm https://github.com/@@REPOSITORY@@/releases/latest/download/@@NAME@@-installer.ps1 | iex
#
# Set $env:@@PREFIX@@_VERSION to install a specific version and $env:@@PREFIX@@_INSTALL_DIR
# to choose the destination. The download is checked against the release's
# SHA256SUMS, and the install directory is added to your user PATH.
param(
    [string] $Version = $env:@@PREFIX@@_VERSION,
    [string] $InstallDir = $env:@@PREFIX@@_INSTALL_DIR
)

$ErrorActionPreference = "Stop"
$previousProgressPreference = $ProgressPreference
$ProgressPreference = "SilentlyContinue"

# Windows can hold an executable briefly after it exits, and antivirus scanners
# open new files, so replacing a binary retries for a few seconds.
function Move-StagedFile {
    param(
        [Parameter(Mandatory = $true)] [string] $Source,
        [Parameter(Mandatory = $true)] [string] $Destination
    )

    for ($attempt = 1; $attempt -le 20; $attempt++) {
        try {
            Move-Item $Source $Destination -Force
            return
        } catch {
            if ($attempt -eq 20) {
                throw "@@NAME@@ installer: could not replace $Destination. Stop any running @@NAME@@ and retry. Last error: $($_.Exception.Message)"
            }
            Start-Sleep -Milliseconds 250
        }
    }
}

if ([string]::IsNullOrWhiteSpace($Version)) {
    $Version = "latest"
}
if ([string]::IsNullOrWhiteSpace($InstallDir)) {
    $InstallDir = Join-Path $env:LOCALAPPDATA "Programs\@@NAME@@\bin"
}

$osArchitecture = [System.Runtime.InteropServices.RuntimeInformation]::OSArchitecture.ToString()
switch ($osArchitecture) {
    "X64" { $architecture = "x64" }
    "Arm64" { $architecture = "arm64" }
    default { throw "@@NAME@@ installer: unsupported Windows architecture: $osArchitecture" }
}
$supported = @(@@WINDOWS_TARGETS@@)
if ($supported -notcontains "windows-$architecture") {
    throw "@@NAME@@ installer: there is no windows-$architecture build of @@NAME@@"
}

$repository = if ([string]::IsNullOrWhiteSpace($env:@@PREFIX@@_REPOSITORY)) { "@@REPOSITORY@@" } else { $env:@@PREFIX@@_REPOSITORY }
if (-not [string]::IsNullOrWhiteSpace($env:@@PREFIX@@_DOWNLOAD_BASE)) {
    $base = $env:@@PREFIX@@_DOWNLOAD_BASE.TrimEnd("/")
} elseif ($Version -eq "latest") {
    $base = "https://github.com/$repository/releases/latest/download"
} else {
    $base = "https://github.com/$repository/releases/download/v$($Version.TrimStart('v'))"
}

$asset = "@@NAME@@-windows-$architecture.zip"
$workDir = Join-Path ([System.IO.Path]::GetTempPath()) ("@@NAME@@-install-" + [guid]::NewGuid())
$archive = Join-Path $workDir $asset
$checksums = Join-Path $workDir "SHA256SUMS"
$payload = Join-Path $workDir "payload"
$binaries = @(@@WINDOWS_BINARIES@@)
$staged = @()

try {
    New-Item -ItemType Directory -Path $workDir | Out-Null

    Write-Host "Downloading $asset..."
    Invoke-WebRequest "$base/$asset" -OutFile $archive -UseBasicParsing
    Invoke-WebRequest "$base/SHA256SUMS" -OutFile $checksums -UseBasicParsing

    $escaped = [regex]::Escape($asset)
    $line = Get-Content $checksums | Where-Object { $_ -match "^([0-9a-fA-F]{64})\s+\*?$escaped$" } | Select-Object -First 1
    if ($null -eq $line) {
        throw "@@NAME@@ installer: SHA256SUMS has no entry for $asset"
    }
    $expected = ([regex]::Match($line, "^[0-9a-fA-F]{64}")).Value.ToLowerInvariant()
    $actual = (Get-FileHash -Algorithm SHA256 $archive).Hash.ToLowerInvariant()
    if ($actual -ne $expected) {
        throw "@@NAME@@ installer: checksum verification failed for $asset"
    }

    Expand-Archive -Path $archive -DestinationPath $payload -Force
    New-Item -ItemType Directory -Path $InstallDir -Force | Out-Null

    foreach ($binary in $binaries) {
        $source = Join-Path $payload $binary
        if (-not (Test-Path $source -PathType Leaf)) {
            throw "@@NAME@@ installer: $asset did not contain $binary"
        }
        $stage = Join-Path $InstallDir (".$([System.IO.Path]::GetFileNameWithoutExtension($binary))." + [guid]::NewGuid() + ".new.exe")
        Copy-Item $source $stage
        $staged += $stage
    }

    $installedVersion = & $staged[0] @@VERSION_ARGS@@
    for ($index = 0; $index -lt $binaries.Count; $index++) {
        Move-StagedFile -Source $staged[$index] -Destination (Join-Path $InstallDir $binaries[$index])
    }
    $staged = @()

    if ($env:@@PREFIX@@_NO_PATH_UPDATE -ne "1") {
        $userPath = [Environment]::GetEnvironmentVariable("Path", "User")
        $entries = @($userPath -split ";" | Where-Object { -not [string]::IsNullOrWhiteSpace($_) })
        $present = $entries | Where-Object { [string]::Equals($_.TrimEnd("\"), $InstallDir.TrimEnd("\"), [StringComparison]::OrdinalIgnoreCase) }
        if (-not $present) {
            [Environment]::SetEnvironmentVariable("Path", (($entries + $InstallDir) -join ";"), "User")
        }
    }
    if (-not (($env:Path -split ";") -contains $InstallDir)) {
        $env:Path = "$InstallDir;$env:Path"
    }

    Write-Host "Installed $installedVersion in $InstallDir"
@@NOTES@@
} finally {
    $ProgressPreference = $previousProgressPreference
    foreach ($file in $staged) {
        if (Test-Path $file) { Remove-Item $file -Force }
    }
    if (Test-Path $workDir) {
        Remove-Item $workDir -Recurse -Force
    }
}
