#!/bin/sh
# Installs @@NAME@@ from its GitHub release. Generated by leduftw/playbook.
#
#   curl -fsSL https://github.com/@@REPOSITORY@@/releases/latest/download/@@NAME@@-installer.sh | sh
#
# Set @@PREFIX@@_VERSION to install a specific version and @@PREFIX@@_INSTALL_DIR to
# choose the destination. Every download is checked against the release's
# SHA256SUMS, and the installer never runs sudo.
#
# The whole body lives in main, called on the very last line. A shell reading a
# pipe runs each command as it arrives, so a connection that drops midway would
# otherwise run whatever prefix of the script had arrived.

set -eu

work_dir=
staged=

cleanup() {
  for file in $staged; do rm -f -- "$file"; done
  [ -z "$work_dir" ] || rm -rf -- "$work_dir"
}

fail() {
  echo "@@NAME@@ installer: $*" >&2
  exit 1
}

version_at_least() {
  old_ifs=$IFS
  IFS=.
  # shellcheck disable=SC2086 # splitting on dots is the point
  set -- $1
  c1=${1:-0} c2=${2:-0} c3=${3:-0}
  # shellcheck disable=SC2086
  set -- $minimum
  m1=${1:-0} m2=${2:-0} m3=${3:-0}
  IFS=$old_ifs
  [ "$c1" -gt "$m1" ] && return 0
  [ "$c1" -lt "$m1" ] && return 1
  [ "$c2" -gt "$m2" ] && return 0
  [ "$c2" -lt "$m2" ] && return 1
  [ "$c3" -ge "$m3" ]
}

main() {
  repository=${@@PREFIX@@_REPOSITORY:-@@REPOSITORY@@}
  requested=${@@PREFIX@@_VERSION:-latest}

  command -v curl >/dev/null 2>&1 || fail "curl is required"

  case $(uname -s) in
    Darwin)
      platform=macos
      extension=zip
      ;;
    Linux)
      platform=linux
      extension=tar.gz
      ;;
    *) fail "unsupported operating system: $(uname -s)" ;;
  esac

  case $(uname -m) in
    arm64 | aarch64) architecture=arm64 ;;
    x86_64 | amd64) architecture=x64 ;;
    *) fail "unsupported architecture: $(uname -m)" ;;
  esac

  targets=" @@TARGETS@@ "
  case $targets in
    *" $platform-$architecture "*) ;;
    *) fail "there is no $platform-$architecture build of @@NAME@@" ;;
  esac

  minimum="@@MACOS_MINIMUM@@"
  if [ "$platform" = macos ] && [ -n "$minimum" ]; then
    current=$(sw_vers -productVersion)
    version_at_least "$current" || fail "macOS $minimum or newer is required; this Mac runs $current"
  fi
  if [ "$platform" = linux ]; then
    if [ -e /etc/alpine-release ] \
      || { command -v ldd >/dev/null 2>&1 && ldd --version 2>&1 | grep -qi musl; }; then
      fail "the Linux build needs glibc; musl systems such as Alpine aren't supported"
    fi
  fi

  if [ -n "${@@PREFIX@@_DOWNLOAD_BASE:-}" ]; then
    base=${@@PREFIX@@_DOWNLOAD_BASE%/}
  elif [ "$requested" = latest ]; then
    base="https://github.com/$repository/releases/latest/download"
  else
    base="https://github.com/$repository/releases/download/v${requested#v}"
  fi

  if [ -n "${@@PREFIX@@_INSTALL_DIR:-}" ]; then
    install_dir=$@@PREFIX@@_INSTALL_DIR
  elif [ -d /usr/local/bin ] && [ -w /usr/local/bin ]; then
    install_dir=/usr/local/bin
  else
    : "${HOME:?HOME must be set, or set @@PREFIX@@_INSTALL_DIR}"
    install_dir=$HOME/.local/bin
  fi

  asset="@@NAME@@-$platform-$architecture.$extension"
  work_dir=$(mktemp -d "${TMPDIR:-/tmp}/@@NAME@@-install.XXXXXX")
  trap cleanup EXIT HUP INT TERM

  echo "Downloading $asset..."
  curl --fail --silent --show-error --location "$base/$asset" --output "$work_dir/$asset"
  curl --fail --silent --show-error --location "$base/SHA256SUMS" --output "$work_dir/SHA256SUMS"

  expected=$(awk -v asset="$asset" '$2 == asset || $2 == "*" asset { print $1; exit }' "$work_dir/SHA256SUMS")
  [ -n "$expected" ] || fail "SHA256SUMS has no entry for $asset"
  if command -v sha256sum >/dev/null 2>&1; then
    actual=$(sha256sum "$work_dir/$asset" | awk '{ print $1 }')
  elif command -v shasum >/dev/null 2>&1; then
    actual=$(shasum -a 256 "$work_dir/$asset" | awk '{ print $1 }')
  else
    fail "sha256sum or shasum is needed to verify the download"
  fi
  [ "$actual" = "$expected" ] || fail "checksum verification failed for $asset"

  payload="$work_dir/payload"
  mkdir -p "$payload"
  if [ "$extension" = zip ]; then
    if command -v ditto >/dev/null 2>&1; then
      ditto -x -k "$work_dir/$asset" "$payload"
    else
      unzip -q "$work_dir/$asset" -d "$payload"
    fi
  else
    tar -xzf "$work_dir/$asset" -C "$payload"
  fi

  binaries="@@BINARIES@@"
  if [ "$platform" = macos ]; then
    binaries="$binaries @@MACOS_BINARIES@@"
  fi

  # Stage every binary next to its destination first, so an upgrade replaces
  # each one with a single rename and never leaves a half-copied file behind.
  mkdir -p "$install_dir"
  for binary in $binaries; do
    [ -f "$payload/$binary" ] || fail "$asset did not contain $binary"
    install -m 755 "$payload/$binary" "$install_dir/.$binary.$$.new"
    staged="$staged $install_dir/.$binary.$$.new"
  done
  installed=$("$install_dir/.@@MAIN@@.$$.new" @@VERSION_ARGS@@)
  for binary in $binaries; do
    mv -f "$install_dir/.$binary.$$.new" "$install_dir/$binary"
  done
  staged=
  echo "Installed $installed in $install_dir"

  case :${PATH:-}: in
    *:"$install_dir":*) ;;
    *)
      echo "Add $install_dir to PATH, then open a new terminal:"
      echo "  export PATH=\"$install_dir:\$PATH\""
      ;;
  esac
@@NOTES@@
}

main "$@"
